title = "TweetCraft Gitleaks Configuration"

# Extend the base configuration
[extend]
useDefault = true

# Custom allowlist for known safe patterns
[allowlist]
description = "Allowlisted patterns"
paths = [
  '''node_modules''',
  '''\.git''',
  '''dist/.*\.map''',
  '''build/.*\.map''',
  '''test/fixtures'''
]

# Allow certain files that may contain example keys
files = [
  '''README\.md''',
  '''CLAUDE\.md''',
  '''\.env\.example''',
  '''docs/.*\.md'''
]

# Custom patterns to exclude (false positives)
regexes = [
  '''process\.env\.[A-Z_]+''',  # Environment variable references are OK
  '''OPENROUTER_API_KEY''',      # Variable name mentions are OK
  '''EXA_API_KEY''',              # Variable name mentions are OK
  '''example[_-]?key''',          # Example keys are OK
  '''test[_-]?api[_-]?key'''     # Test keys are OK
]

# Additional rules for TweetCraft specific secrets
[[rules]]
id = "openrouter-api-key"
description = "OpenRouter API Key"
regex = '''sk-or-v1-[a-f0-9]{64}'''
tags = ["api", "openrouter"]

[[rules]]
id = "openai-api-key"
description = "OpenAI API Key"
regex = '''sk-[a-zA-Z0-9]{48}'''
tags = ["api", "openai"]

[[rules]]
id = "exa-api-key"
description = "Exa API Key"
regex = '''exa_[a-zA-Z0-9]{32,}'''
tags = ["api", "exa"]

[[rules]]
id = "twitter-bearer-token"
description = "Twitter Bearer Token"
regex = '''Bearer [a-zA-Z0-9%]{100,}'''
tags = ["api", "twitter"]

[[rules]]
id = "chrome-extension-key"
description = "Chrome Extension Private Key"
regex = '''-----BEGIN (RSA |EC )?PRIVATE KEY-----'''
tags = ["chrome", "private-key"]

# Ensure dist/ folder is strictly checked
[[rules]]
id = "dist-folder-secrets"
description = "Any secrets in dist/ folder"
regex = '''(api[_-]?key|secret|token|password|bearer|credential)['"]?\s*[:=]\s*['"][^'"]+['"]'''
path = '''dist/.*'''
tags = ["dist", "build"]